"""Baseline schema — all tables from docs/02-architecture.md §Data model.

Revision ID: d5d0e6b3dd72
Revises:
Create Date: 2026-07-12

Autogenerated against Postgres 16, then reviewed by hand (typing modernised,
enum-type drops added to downgrade).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5d0e6b3dd72"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Native Postgres enum types created by this revision (create_table creates
# them implicitly; downgrade must drop them explicitly).
ENUM_TYPE_NAMES = (
    "user_role",
    "box_office_provider",
    "box_office_connection_status",
    "survey_focus",
    "allocation_status",
    "invitation_status",
    "email_event_type",
    "suppression_reason",
    "insight_report_status",
)


def upgrade() -> None:
    """Create the full baseline schema."""
    op.create_table(
        "organisations",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("sender_domain", sa.String(), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organisations_slug")),
    )
    op.create_table(
        "survey_templates",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "focus",
            sa.Enum("quality", "impact", "feedback", "profile", name="survey_focus"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_survey_templates")),
        sa.UniqueConstraint("slug", name=op.f("uq_survey_templates_slug")),
    )
    op.create_table(
        "box_office_connections",
        sa.Column("provider", sa.Enum("spektrix", name="box_office_provider"), nullable=False),
        sa.Column("credentials", sa.LargeBinary(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "error", "disabled", name="box_office_connection_status"),
            nullable=False,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_box_office_connections_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_box_office_connections")),
    )
    op.create_index(
        op.f("ix_box_office_connections_org_id"), "box_office_connections", ["org_id"], unique=False
    )
    op.create_table(
        "customers",
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("opted_out_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_customers_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("org_id", "external_id", name=op.f("uq_customers_org_id_external_id")),
    )
    op.create_index(op.f("ix_customers_org_id"), "customers", ["org_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_events_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("org_id", "external_id", name=op.f("uq_events_org_id_external_id")),
    )
    op.create_index(op.f("ix_events_org_id"), "events", ["org_id"], unique=False)
    op.create_table(
        "suppressions",
        sa.Column("email_hash", sa.String(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "unsubscribe",
                "bounce",
                "complaint",
                "box_office_opt_out",
                name="suppression_reason",
            ),
            nullable=False,
        ),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_suppressions_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppressions")),
    )
    op.create_index(op.f("ix_suppressions_org_id"), "suppressions", ["org_id"], unique=False)
    op.create_index(
        "ix_suppressions_org_id_email_hash", "suppressions", ["org_id", "email_hash"], unique=False
    )
    op.create_table(
        "template_versions",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("question_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("insight_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sample_dataset", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_survey_ref", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["survey_templates.id"],
            name=op.f("fk_template_versions_template_id_survey_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_versions")),
        sa.UniqueConstraint(
            "template_id", "version", name=op.f("uq_template_versions_template_id_version")
        ),
    )
    op.create_index(
        op.f("ix_template_versions_template_id"), "template_versions", ["template_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("member", "admin", name="user_role"), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_users_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("org_id", "email", name=op.f("uq_users_org_id_email")),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_table(
        "customer_tags",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_customer_tags_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("customer_id", "tag", name=op.f("pk_customer_tags")),
    )
    op.create_table(
        "event_instances",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("venue_name", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_instances_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_instances")),
        sa.UniqueConstraint(
            "event_id", "external_id", name=op.f("uq_event_instances_event_id_external_id")
        ),
    )
    op.create_index(
        op.f("ix_event_instances_event_id"), "event_instances", ["event_id"], unique=False
    )
    op.create_table(
        "allocations",
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("instance_id", sa.Uuid(), nullable=True),
        sa.Column("send_delay_hours", sa.Integer(), nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "sending",
                "collecting",
                "complete",
                "cancelled",
                name="allocation_status",
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(event_id IS NULL) != (instance_id IS NULL)",
            name=op.f("ck_allocations_exactly_one_target"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_allocations_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_allocations_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["event_instances.id"],
            name=op.f("fk_allocations_instance_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_allocations_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["template_versions.id"],
            name=op.f("fk_allocations_template_version_id_template_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(op.f("ix_allocations_event_id"), "allocations", ["event_id"], unique=False)
    op.create_index(
        op.f("ix_allocations_instance_id"), "allocations", ["instance_id"], unique=False
    )
    op.create_index(op.f("ix_allocations_org_id"), "allocations", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_allocations_template_version_id"),
        "allocations",
        ["template_version_id"],
        unique=False,
    )
    op.create_table(
        "attendances",
        sa.Column("instance_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("tickets", sa.Integer(), nullable=False),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_attendances_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["event_instances.id"],
            name=op.f("fk_attendances_instance_id_event_instances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_attendances_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendances")),
        sa.UniqueConstraint(
            "instance_id", "customer_id", name=op.f("uq_attendances_instance_id_customer_id")
        ),
    )
    op.create_index(
        op.f("ix_attendances_customer_id"), "attendances", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_attendances_instance_id"), "attendances", ["instance_id"], unique=False
    )
    op.create_index(op.f("ix_attendances_org_id"), "attendances", ["org_id"], unique=False)
    op.create_table(
        "insight_reports",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "generating", "ready", "failed", name="insight_report_status"),
            nullable=False,
        ),
        sa.Column("charts_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("narrative", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
            name=op.f("fk_insight_reports_allocation_id_allocations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_insight_reports_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_insight_reports")),
    )
    op.create_index(
        op.f("ix_insight_reports_allocation_id"), "insight_reports", ["allocation_id"], unique=False
    )
    op.create_index(op.f("ix_insight_reports_org_id"), "insight_reports", ["org_id"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "reminded",
                "responded",
                "bounced",
                "suppressed",
                "failed",
                name="invitation_status",
            ),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
            name=op.f("fk_invitations_allocation_id_allocations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_invitations_customer_id_customers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_invitations_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token", name=op.f("uq_invitations_token")),
    )
    op.create_index(
        op.f("ix_invitations_allocation_id"), "invitations", ["allocation_id"], unique=False
    )
    op.create_index(
        op.f("ix_invitations_customer_id"), "invitations", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)
    op.create_table(
        "email_events",
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("delivery", "bounce", "complaint", "open", name="email_event_type"),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
            name=op.f("fk_email_events_invitation_id_invitations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_events")),
    )
    op.create_index(
        op.f("ix_email_events_invitation_id"), "email_events", ["invitation_id"], unique=False
    )
    op.create_table(
        "responses",
        sa.Column("invitation_id", sa.Uuid(), nullable=False),
        sa.Column("engine_response_ref", sa.String(), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invitation_id"],
            ["invitations.id"],
            name=op.f("fk_responses_invitation_id_invitations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organisations.id"],
            name=op.f("fk_responses_org_id_organisations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responses")),
        sa.UniqueConstraint("invitation_id", name=op.f("uq_responses_invitation_id")),
    )
    op.create_index(op.f("ix_responses_org_id"), "responses", ["org_id"], unique=False)


def downgrade() -> None:
    """Drop the full baseline schema, including the native enum types."""
    op.drop_index(op.f("ix_responses_org_id"), table_name="responses")
    op.drop_table("responses")
    op.drop_index(op.f("ix_email_events_invitation_id"), table_name="email_events")
    op.drop_table("email_events")
    op.drop_index(op.f("ix_invitations_org_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_customer_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_allocation_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_insight_reports_org_id"), table_name="insight_reports")
    op.drop_index(op.f("ix_insight_reports_allocation_id"), table_name="insight_reports")
    op.drop_table("insight_reports")
    op.drop_index(op.f("ix_attendances_org_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_instance_id"), table_name="attendances")
    op.drop_index(op.f("ix_attendances_customer_id"), table_name="attendances")
    op.drop_table("attendances")
    op.drop_index(op.f("ix_allocations_template_version_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_org_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_instance_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_event_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_event_instances_event_id"), table_name="event_instances")
    op.drop_table("event_instances")
    op.drop_table("customer_tags")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_template_versions_template_id"), table_name="template_versions")
    op.drop_table("template_versions")
    op.drop_index("ix_suppressions_org_id_email_hash", table_name="suppressions")
    op.drop_index(op.f("ix_suppressions_org_id"), table_name="suppressions")
    op.drop_table("suppressions")
    op.drop_index(op.f("ix_events_org_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_customers_org_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_box_office_connections_org_id"), table_name="box_office_connections")
    op.drop_table("box_office_connections")
    op.drop_table("survey_templates")
    op.drop_table("organisations")
    for enum_type_name in ENUM_TYPE_NAMES:
        sa.Enum(name=enum_type_name).drop(op.get_bind(), checkfirst=True)
